apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cnj-logging-resources.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "cnj-logging-resources.name" . }}-postgres
    helm.sh/chart: {{ include "cnj-logging-resources.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  postgresql-postgres-password: {{ required "missing required value postgresql.postgresqlPostgresPassword" .Values.postgresql.postgresqlPostgresPassword | b64enc }}
  postgresql-password: {{ required "missing required value postgresql.postgresqlPassword" .Values.postgresql.postgresqlPassword | b64enc }}
  postgresql-user: {{ required "missing required value postgresql.postgresqlUsername" .Values.postgresql.postgresqlUsername | b64enc }}
