# Default values for cnj-logging-downstream.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ${docker.image.name}
  tag: ${project.version}
  pullPolicy: IfNotPresent

probes:
  readiness:
    path: /actuator/health
  liveness:
    path: /actuator/health

nameOverride: ""
fullnameOverride: ""
partOfOverride: "cnj-rest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  host: "${k8s.ingress.host}"
  paths: ["${k8s.ingress.path}"]

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 756Mi

# security configuration (Open ID Connect)
security:
  oidc:
    jwksUri: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain/protocol/openid-connect/certs"
    issuer: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain"
